version: '3'
services:
  ms-dolphins:
    container_name: ms-dolphins
    restart: on-failure
    build:
      context: ./ms-dolphins
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      PORT: ${PORT}
      DOMAIN: ${DOMAIN}
    depends_on:
      - ms-dolphins

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres-data:
  pgadmin-data:
